### ISSUE TITLE
is_page_locked_for_current_user()

### ISSUE THREAD

**Issue by adriantoll** [gyrus/Lock-Pages#3]
This function uses `$_GET['action']` when `$screen = get_current_screen()` returns an object `$screen->action` that seemingly could be used instead.  Is there a reason for preferring `$_GET['action']` over `$screen->action`?

**Comment by adriantoll** [comment]
(The function is on line 511)

**Comment by gyrus** [comment]
I imagine it's either a little oversight, or the parts of the conditional were done at different times and not integrated. If it works I'm tempted to let it be, unless there's a reason beyond simple consistency to change it?

**Comment by adriantoll** [comment]
No reason beyond simplicity and possibly a very minor performance gain from not using `isset()`.  I have the current release of the plugin and was getting PHP warnings which were fixed in the unreleased 72a1be0 commit.  The fix I'm suggesting came from looking at the `$screen` object and fixing it with `$screen->action` rather than a check for the existence of `$_GET['action']`.

**Comment by gyrus** [comment]
Gotcha. If it's changing something that's unreleased, that's more of a goer I think. I had a quick look at how '$screen->action' gets constructed, and it wasn't 100% clear from the source that it will always equal '$_GET['action']' but I imagine I was reading it wrong. I'll have another look, and if testing works out fine, will make the change.

**Comment by adriantoll** [comment]
Thinking about it a bit more, it's not the same as `$_GET['action']`, but that was actually my issue.  When creating a new page I was getting a warning because `$_GET['action']` wasn't defined.  In that circumstance `$screen->action` _is_ defined and is something like `add` - so it's always available to check to see whether it equals `edit` or not.

**Comment by gyrus** [comment]
Happy to change if it'll work. I think this is where `$screen->action` is defined:

https://core.trac.wordpress.org/browser/tags/4.4.2/src/wp-admin/includes/class-wp-screen.php#L16

I guess the change would be to `$screen->base == 'post' && $screen->action != 'add'` . Am just wary because the recent change was the addition of the `isset( $_GET['action'])`. The test for `$_GET['action'] == 'edit'` has been in the code for ages and I'm wary of a (small) chance of a regression for a (very small) code improvement.
